export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_RESPONSE = "SIGNUP_RESPONSE";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const USERLOGIN_REQUEST = 'USERLOGIN_REQUEST';


