export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_RESPONSE = "SIGNUP_RESPONSE";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const LOGOUT_ACCOUNT = "LOGOUT_ACCOUNT"
export const LOGOUT_RESPONSE = "LOGOUT_RESPONSE"

export const USERLOGIN_REQUEST = "USERLOGIN_REQUEST"
export const USERLOGIN_RESPONSE = "USERLOGIN_RESPONSE"
export const USERLOGOUT_REQUEST = "USERLOGOUT_REQUEST"
export const USERLOGOUT_RESPONSE = "USERLOGOUT_RESPONSE"


// export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";



